http:
  address: ":8080"

database:
  user: "user"
  password: "password"
  host: "postgres"
  port: 5432
  dbname: "orders"
  sslmode: "disable"

nats:
  url: "nats://nats:4222"
  cluster_id: "test-cluster"
  client_id: "order-service"
  subject: "orders"