http:
  address: ":8080"

database:
  user: "user"
  password: "password"
  host: "localhost"
  port: 5432
  dbname: "orders"       
  sslmode: "disable" 

nats:
  url: "nats://localhost:4222"
  cluster_id: "test-cluster"
  client_id: "order-service"
  subject: "orders"