version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d orders"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-p", "4222", "-m", "8222"]

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=orders
      - NATS_URL=nats://nats:4222
    restart: unless-stopped

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    depends_on:
      nats:
        condition: service_started
      app:
        condition: service_started
    environment:
      - NATS_URL=nats://nats:4222
    restart: "no"

volumes:
  postgres_data: